- name: Install Visual Studio Code
  homebrew_cask:
    name: visual-studio-code

- name: Install EditorConfig for VS Code
  shell: >
    code --install-extension EditorConfig.EditorConfig

- name: Install Polacode for VS Code
  shell: >
    code --install-extension pnp.polacode

- name: Install GitLens for VS Code
  shell: >
    code --install-extension eamodio.gitlens

- name: Install Jest Runner
  shell: >
    code --install-extension firsttris.vscode-jest-runner

- name: Install Quit control
  shell: >
    code --install-extension artdiniz.quitcontrol-vscode
