- name: installing Zsh
  homebrew: name=zsh state=latest

- stat: path=$HOME/.oh-my-zsh
  register: cur_dir

- name: installing Oh-My-Zsh
  shell: >
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  when: cur_dir.stat.exists == False

- name: setting up zsh as default shell
  shell: >
    chsh -s /bin/zsh

- name: installing powerlevel10k plugin
  shell: |
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.powerlevel10k
    echo 'source ~/.powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc