- name: "Install Java Version Management (jEnv)"
  homebrew: name=jenv state=latest

- name: "Set up Java Version Management (jEnv)"
  shell: >
    echo 'export PATH="$HOME/.jenv/bin:$PATH"' >> ~/.zshrc
    echo 'eval "$(jenv init -)"' >> ~/.zshrc
  args:
    executable: /bin/bash